
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace CTAIntentModel_v1.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            CTAIntentModel_v1.ModelInput sampleData = new CTAIntentModel_v1.ModelInput()
            {
                Text = @"I want to add travel insurance to my booking.",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"Text: {@"I want to add travel insurance to my booking."}");
            Console.WriteLine($"Label: {@"NewBooking_AddInsurance"}");


            var sortedScoresWithLabel = CTAIntentModel_v1.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
