services:
  postgresql:
    image: postgres:15
    container_name: arcadia_postgresql
    networks:
      - internal_network
    environment:
      POSTGRES_USER: arcadia
      POSTGRES_PASSWORD: arcadia_password
      POSTGRES_DB: arcadia_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  arcadia.api:
    build:
      context: .
      dockerfile: Dockerfile.API
      target: runtime
    container_name: arcadia_api
    networks:
      - internal_network
      - api_webapp_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=arcadia_postgresql;Database=arcadia_db;Username=arcadia;Password=arcadia_password
    depends_on:
      - postgresql
    ports:
      - "5050:5000" # For debugging API locally if needed

  arcadia.webapp:
    build:
      context: .
      dockerfile: Dockerfile.WebApp
    container_name: arcadia_webapp
    networks:
      - api_webapp_network
      - public_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080" # Expose WebApp to localhost (public)

networks:
  internal_network:
    name: arcadia_internal_network
    driver: bridge

  api_webapp_network:
    name: arcadia_api_webapp_network
    driver: bridge

  public_network:
    name: arcadia_public_network
    driver: bridge

volumes:
  pg_data:
    name: arcadia_pg_data
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

