services:
  postgresql:
    image: postgres:17.2-alpine3.20
    container_name: arcadia_postgresql
    networks:
      - internal
    environment:
      POSTGRES_USER: arcadia
      POSTGRES_PASSWORD: arcadia_password
      POSTGRES_DB: arcadia_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  arcadia.api:
    build:
      context: .
      dockerfile: Dockerfile.API
      target: final
    container_name: arcadia_api
    networks:
      - internal
      - public
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=arcadia_postgresql;Database=arcadia_db;Username=arcadia;Password=arcadia_password
      - JWTSETTINGS__SECRET=your-secret-key
      - JWTSETTINGS__ISSUER=your-issuer
      - JWTSETTINGS__AUDIENCE=your-audience
    depends_on:
      - postgresql
    ports:
      - "5050:8080" # Expose API for debugging or public access

  arcadia.webapp:
    build:
      context: .
      dockerfile: Dockerfile.WebApp
      target: final
    container_name: arcadia_webapp
    networks:
      - public
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080" # Expose WebApp to localhost (public)
  
  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: arcadia_pgadmin4
    networks:
      - internal
      - public
    environment:
      - PGADMIN_DEFAULT_EMAIL=arcadia@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=Arcadia123!
    depends_on:
      - postgresql
    ports:
      - "8090:80" # Expose pgAdmin for public access

networks:
  internal:
    name: arcadia_internal_network
    driver: bridge

  public:
    name: arcadia_public_network
    driver: bridge

volumes:
  pg_data:
    name: arcadia_pg_data

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

