services:
  arcadia.webapp:
    build:
      context: .
      dockerfile: Dockerfile.WebApp
      target: final
    container_name: arcadia_webapp
    networks:
      - public
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT_WEBAPP}
      ASPNETCORE_URLS: ${BLAZOR_URLS}
    volumes:
      - webapp_certs:/etc/arcadia/webapp_certs
      - webapp_dataprotection_keys:/etc/arcadia/dataprotection-keys
    ports:
      - "8080:8080"

networks:
  public:
    name: arcadia_public_network
    driver: bridge

volumes:
  webapp_certs:
    name: arcadia_webapp_certs
    external: true
  webapp_dataprotection_keys:
    name: arcadia_webapp_dataprotection_keys
    external: true
