services:
  postgresql:
    image: postgres:17.2-alpine3.20
    container_name: arcadia_postgresql
    networks:
      - internal
    environment:
      POSTGRES_USER: arcadia
      POSTGRES_PASSWORD: arcadia_password
      POSTGRES_DB: arcadia_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "arcadia" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.db-init
    container_name: arcadia_db_init
    networks:
      - internal
    environment:
      - CONNECTION_STRING=Host=arcadia_postgresql;Database=arcadia_db;Username=arcadia;Password=arcadia_password
      - RESET_DB=false # Change to true to reset the database
    depends_on:
      postgresql:
        condition: service_healthy
    restart: "no" # Ensures the container stops after running the migrations

  arcadia.api:
    build:
      context: .
      dockerfile: Dockerfile.API
      target: final
    container_name: arcadia_api
    networks:
      - internal
      - public
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=arcadia_postgresql;Database=arcadia_db;Username=arcadia;Password=arcadia_password
      - JWTSETTINGS__SECRET=your-secret-key
      - JWTSETTINGS__ISSUER=your-issuer
      - JWTSETTINGS__AUDIENCE=your-audience
    depends_on:
      - postgresql
      - db-init
    ports:
      - "5050:8080" # Expose API for debugging or public access

  arcadia.webapp:
    build:
      context: .
      dockerfile: Dockerfile.WebApp
      target: final
    container_name: arcadia_webapp
    networks:
      - public
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080" # Expose WebApp to localhost (public)
  
  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: arcadia_pgadmin4
    networks:
      - internal
      - public
    environment:
      - PGADMIN_DEFAULT_EMAIL=arcadia@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=Arcadia123!
    depends_on:
      - postgresql
    ports:
      - "8090:80" # Expose pgAdmin for public access

networks:
  internal:
    name: arcadia_internal_network
    driver: bridge

  public:
    name: arcadia_public_network
    driver: bridge

volumes:
  pg_data:
    name: arcadia_pg_data
