
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace IntentModelDev02.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            IntentModelDev02.ModelInput sampleData = new IntentModelDev02.ModelInput()
            {
                Text = @"""I want to book a flight to New York.""",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"Text: {@"""I want to book a flight to New York."""}");
            Console.WriteLine($"Label: {@"NewBooking_SelectFlight"}");


            var sortedScoresWithLabel = IntentModelDev02.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
