version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  text_generator:
    build: .
    container_name: text_generator
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE=http://ollama:11434

volumes:
  ollama_data:
