name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker API image
      run: docker build . --file Dockerfile.API --tag arcadia.api:$(date +%s)
    - name: Build the Docker WebApp image
      run: docker build . --file Dockerfile.WebApp --tag arcadia.webapp:$(date +%s)
