name: Docker Build and Compose Up

on:
  push:
    branches:
      - CorporateTravelCompanion-with-intents
  pull_request:
    branches:
      - CorporateTravelCompanion-with-intents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build and start Docker Compose services
      - name: Docker Compose Up
        run: docker-compose up -d
        working-directory: ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama

      # Step 5: Wait for the Python script to complete
      - name: Wait for Text Generation to Complete
        run: |
          docker logs -f text_generator || true
        working-directory: ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama

      # Step 6: Copy the generated text file from the container
      - name: Copy Generated Text File
        run: |
          docker cp text_generator:/app/generated_texts.txt ./generated_texts.txt
        working-directory: ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama

      # Step 7: Shutdown Docker Compose services
      - name: Docker Compose Down
        run: docker-compose down
        working-directory: ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama

      # Step 8: Upload the generated text file as an artifact
      - name: Upload Generated Text File
        uses: actions/upload-artifact@v4
        with:
          name: generated-texts
          path: ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama/generated_texts.txt
