name: Docker Build

on:
  push:
    branches:
      - CorporateTravelCompanion-with-intents
  pull_request:
    branches:
      - CorporateTravelCompanion-with-intents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Step 3: Build the Docker image using github.workspace
      - name: Build Docker image
        run: docker build -t text-generator ${{ github.workspace }}/Arcadia.ML/ngpt2-ollama